In [ ]:
import numpy as np

In [ ]:
print(np.__version__)
np.show_config()


1.21.6
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSS

In [ ]:
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
" import numpy; 
numpy.info(numpy.add)"


SyntaxError: ignored

In [ ]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
Z = np.arange(10,51)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [ ]:
Z = np.arange(50)
Z[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [ ]:
Z = np.arange(15).reshape(3,5)
print(Z)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [ ]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)


(array([0, 1, 4]),)


In [ ]:
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
import numpy as np

Z = np.random.random((3,3,3))
print(Z)


[[[0.03408618 0.06844247 0.00928948]
  [0.81900203 0.97732725 0.68678106]
  [0.41755773 0.1987522  0.88030135]]

 [[0.51379805 0.37512884 0.39269799]
  [0.52201672 0.15326531 0.18513793]
  [0.69015304 0.01175494 0.56429513]]

 [[0.77826941 0.50567533 0.49246238]
  [0.11901559 0.04533634 0.48072218]
  [0.43358707 0.74055766 0.90667175]]]


In [ ]:
Z = np.random.random (30)
type = int
print (Z)
m = Z.mean()
print(m)

[0.42379439 0.04531275 0.33045981 0.13168837 0.35434727 0.8325721
 0.96188048 0.93913966 0.85975754 0.97006897 0.25801295 0.96891004
 0.80476761 0.77298522 0.75138425 0.04295801 0.81997949 0.96306251
 0.50765932 0.30471    0.80847801 0.15983951 0.67026926 0.2211196
 0.94512126 0.35671004 0.0514575  0.53256148 0.86168533 0.39490864]
0.5681867113580314


In [ ]:
Z = np.random.random_integers (30)

AttributeError: ignored

In [ ]:
import numpy as np

print(np.__version__)

1.21.6


In [ ]:
Z = np.random.random((10,10))

Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

0.004571994004430868 0.9993833112973126


In [ ]:
import numpy as np

arr = np.array(42)

print(arr)

42


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [ ]:
import numpy as np

arr = np.array((1, 2, 3, 4, 5))

print(arr)

[1 2 3 4 5]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))


[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)

NameError: ignored

In [ ]:
import numpy as np

Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
import numpy as np

Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.49415698 0.57064174 0.71901642 0.40618172 0.55411807 0.08954338
 0.29696187 0.         0.04230567 0.25321782]


In [ ]:
Z = np.random.random(10)


NameError: ignored

In [ ]:
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [ ]:
Z = np.diag(np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]]


In [ ]:
import numpy as np
Z = np.random.random(10) 
Z[Z.argmax()] = 5 
print(Z)

[0.28278397 0.04201909 0.1848159  0.11808656 0.43393512 0.28843952
 0.44555758 0.5709447  0.26147807 5.        ]
